name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main # This means the workflow runs whenever you push to your 'main' branch

permissions:
  contents: write # Needed for the workflow to push the built site
  pages: write    # Needed for GitHub Pages deployment
  id-token: write # For OIDC features, generally good to include for Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment-url.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # IMPORTANT: Match your actual Blazor project's .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Blazor WASM
      run: dotnet publish -c Release -o publish --nologo

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5
      with:
        enablement: true

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: publish/wwwroot # This is where your compiled Blazor app's static files are

    - name: Deploy to GitHub Pages
      id: deployment-url
      uses: actions/deploy-pages@v4
